// Layout
// Только root layout может иметь теги html, body

import { Providers } from "./redux/provider"; // оборачиваем в provider

import type { Metadata } from "next";
import "@/styles/_globals.scss";

import TemplateHeader from "@/components/templates/templateHeader";

// SEO Метаданные (Head) (их много, см. документацию)
export const metadata: Metadata = {
  title: "Next Reference",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,regular,500,600,700,800,900,200italic,300italic,italic,500italic,600italic,700italic,800italic,900italic" rel="stylesheet" />
      </head>
      <body>
        <div className="_wrapper">
        <TemplateHeader headerNav={[
          {id: 1, href: "https://google.com", text: "Home"},
          {id: 2, href: "https://google.com", text: "Blog"},
          {id: 3, href: "https://google.com", text: "Portfolio"},
          {id: 4, href: "https://google.com", text: "Contacts"},
          ]}/>

        <Providers>
          {children}
        </Providers>

        <footer>d</footer>
        </div>
      </body>
    </html>
  );
}
