// Layout
// Только root layout может иметь теги html, body

import { Providers } from "./redux/provider"; // оборачиваем в provider

import type { Metadata } from "next";
import "@/styles/_globals.scss";

import TemplateHeader from "@/components/templates/templateHeader";
import TemplateHLoading from "@/components/templates/templateLoading";
import TemplateFade from "@/components/templates/templateFade";
import TemplatePopup from "@/components/templates/templatePopup";
import TemplateFooter from "@/components/templates/templateFooter";

// SEO Метаданные (Head) (их много, см. документацию)
export const metadata: Metadata = {
    title: "ASD-Nerud",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,regular,500,600,700,800,900,200italic,300italic,italic,500italic,600italic,700italic,800italic,900italic"
                    rel="stylesheet"
                />
            </head>
            <body>
                <Providers>
                    {/* <TemplateFade /> */}
                    <div className="_wrapper">
                        <TemplateHeader
                            headerNav={[
                                {
                                    id: 1,
                                    href: "https://google.com",
                                    text: "Главная",
                                },
                                {
                                    id: 2,
                                    href: "https://google.com",
                                    text: "Услуги",
                                },
                                {
                                    id: 3,
                                    href: "https://google.com",
                                    text: "Контакты",
                                },
                                {
                                    id: 4,
                                    href: "https://google.com",
                                    text: "Портфолио",
                                },
                            ]}
                        />
                        <TemplatePopup />
                        {children}

                        <TemplateFooter />
                    </div>
                </Providers>
            </body>
        </html>
    );
}
